# Generated by Django 4.1.5 on 2023-01-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudDeveloper', '0004_alter_tbl_mahasiswadetails_mahasiswaage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mahasiswadetails',
            name='mahasiswaAge',
            field=models.CharField(max_length=200),
        ),
    ]
