# Generated by Django 4.1.5 on 2023-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudDeveloper', '0007_rename_tbl_mahasiswadetails_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerName', models.CharField(max_length=150)),
                ('developerAge', models.CharField(max_length=200)),
                ('developerSkill', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
