# Generated by Django 4.1.5 on 2023-01-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudMahasiswa', '0002_alter_tbl_mahasiswadetails_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mahasiswadetails',
            name='mahasiswaAge',
            field=models.IntegerField(max_length=10),
        ),
    ]
