# Generated by Django 4.1.5 on 2023-01-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudMahasiswa', '0005_alter_tbl_mahasiswadetails_mahasiswaage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tbl_mahasiswadetails',
            managers=[
            ],
        ),
    ]
