# Generated by Django 4.1.5 on 2023-01-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudMahasiswa', '0006_alter_tbl_mahasiswadetails_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_Mahasiswadetails',
            new_name='Mahasiswa',
        ),
    ]
